org: jhosepluna
service: estimaciones-api

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::946503249480:role/LabRole

functions:
  listar:
    handler: ListarEstimaciones.lambda_handler
    events:
      - http:
          path: /estimaciones/listar
          method: get
          cors: true
          integration: lambda
  buscar:
    handler: BuscarEstimacion.lambda_handler
    events:
      - http:
          path: /estimaciones/buscar
          method: post
          cors: true
          integration: lambda
  crear:
    handler: CrearEstimacion.lambda_handler
    events:
      - http:
          path: /estimaciones/crear
          method: post
          cors: true
          integration: lambda
  modificar:
    handler: ModificarEstimacion.lambda_handler
    events:
      - http:
          path: /estimaciones/modificar
          method: put
          cors: true
          integration: lambda
  eliminar:
    handler: EliminarEstimacion.lambda_handler
    events:
      - http:
          path: /estimaciones/eliminar
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    EstimacionesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: estimaciones
        AttributeDefinitions:
          - AttributeName: estimacion_id
            AttributeType: S
        KeySchema:
          - AttributeName: estimacion_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: Name
            Value: estimaciones-table
